// flow-typed signature: cd1a397c07c8e3e3776bba1742cd0cb8
// flow-typed version: <<STUB>>/@babel/plugin-proposal-json-strings_v^7.2.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-json-strings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-json-strings' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-json-strings/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-json-strings/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-json-strings/lib'>;
}
declare module '@babel/plugin-proposal-json-strings/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-json-strings/lib'>;
}
