// flow-typed signature: 47dac5278e0150bbc5ac3ef66e5dd86b
// flow-typed version: <<STUB>>/@babel/plugin-proposal-optional-catch-binding_v^7.2.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-optional-catch-binding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-optional-catch-binding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-optional-catch-binding/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-optional-catch-binding/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-optional-catch-binding/lib'>;
}
declare module '@babel/plugin-proposal-optional-catch-binding/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-optional-catch-binding/lib'>;
}
