// flow-typed signature: 55facbaa662fa48dc199860a50beb915
// flow-typed version: <<STUB>>/@babel/plugin-proposal-unicode-property-regex_v^7.4.4/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-unicode-property-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-unicode-property-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-unicode-property-regex/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-unicode-property-regex/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/lib'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/lib'>;
}
