// flow-typed signature: e643065508e8852bc45d4acd94d0b254
// flow-typed version: <<STUB>>/dictionary-en_v^2.1.1/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dictionary-en'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dictionary-en' {
  declare module.exports: any;
}
