// flow-typed signature: 9a2ff7914eb5619979b1402a9d3b7c83
// flow-typed version: <<STUB>>/remark-lint-checkbox-character-style_v1.0.3/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-checkbox-character-style'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-checkbox-character-style' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-checkbox-character-style/index' {
  declare module.exports: $Exports<'remark-lint-checkbox-character-style'>;
}
declare module 'remark-lint-checkbox-character-style/index.js' {
  declare module.exports: $Exports<'remark-lint-checkbox-character-style'>;
}
