// flow-typed signature: e63c0cdd2146dae63b4b5b7aad64b755
// flow-typed version: <<STUB>>/retext-spell_v^2.4.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-spell'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-spell' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-spell/index' {
  declare module.exports: $Exports<'retext-spell'>;
}
declare module 'retext-spell/index.js' {
  declare module.exports: $Exports<'retext-spell'>;
}
