// flow-typed signature: a3d793f872cff26294d75e0015c69391
// flow-typed version: <<STUB>>/retext-equality_v^3.8.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-equality'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-equality' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'retext-equality/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'retext-equality/index' {
  declare module.exports: $Exports<'retext-equality'>;
}
declare module 'retext-equality/index.js' {
  declare module.exports: $Exports<'retext-equality'>;
}
declare module 'retext-equality/lib/index.js' {
  declare module.exports: $Exports<'retext-equality/lib/index'>;
}
