// flow-typed signature: 6c54d0ed060924d32bbb46c821e0b106
// flow-typed version: <<STUB>>/retext-profanities_v^5.0.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-profanities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-profanities' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'retext-profanities/ar-latn' {
  declare module.exports: any;
}

declare module 'retext-profanities/en' {
  declare module.exports: any;
}

declare module 'retext-profanities/es' {
  declare module.exports: any;
}

declare module 'retext-profanities/factory' {
  declare module.exports: any;
}

declare module 'retext-profanities/fr' {
  declare module.exports: any;
}

declare module 'retext-profanities/it' {
  declare module.exports: any;
}

declare module 'retext-profanities/pt-br' {
  declare module.exports: any;
}

// Filename aliases
declare module 'retext-profanities/ar-latn.js' {
  declare module.exports: $Exports<'retext-profanities/ar-latn'>;
}
declare module 'retext-profanities/en.js' {
  declare module.exports: $Exports<'retext-profanities/en'>;
}
declare module 'retext-profanities/es.js' {
  declare module.exports: $Exports<'retext-profanities/es'>;
}
declare module 'retext-profanities/factory.js' {
  declare module.exports: $Exports<'retext-profanities/factory'>;
}
declare module 'retext-profanities/fr.js' {
  declare module.exports: $Exports<'retext-profanities/fr'>;
}
declare module 'retext-profanities/index' {
  declare module.exports: $Exports<'retext-profanities'>;
}
declare module 'retext-profanities/index.js' {
  declare module.exports: $Exports<'retext-profanities'>;
}
declare module 'retext-profanities/it.js' {
  declare module.exports: $Exports<'retext-profanities/it'>;
}
declare module 'retext-profanities/pt-br.js' {
  declare module.exports: $Exports<'retext-profanities/pt-br'>;
}
