// flow-typed signature: 562b752b1b5bb63a4508c1881368275a
// flow-typed version: <<STUB>>/retext-indefinite-article_v^1.1.7/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-indefinite-article'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-indefinite-article' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'retext-indefinite-article/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'retext-indefinite-article/index' {
  declare module.exports: $Exports<'retext-indefinite-article'>;
}
declare module 'retext-indefinite-article/index.js' {
  declare module.exports: $Exports<'retext-indefinite-article'>;
}
declare module 'retext-indefinite-article/lib/index' {
  declare module.exports: $Exports<'retext-indefinite-article/lib'>;
}
declare module 'retext-indefinite-article/lib/index.js' {
  declare module.exports: $Exports<'retext-indefinite-article/lib'>;
}
