// flow-typed signature: 52a78e794c7b823cbbcb42428ebb27d2
// flow-typed version: <<STUB>>/retext-sentence-spacing_v^2.1.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-sentence-spacing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-sentence-spacing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-sentence-spacing/index' {
  declare module.exports: $Exports<'retext-sentence-spacing'>;
}
declare module 'retext-sentence-spacing/index.js' {
  declare module.exports: $Exports<'retext-sentence-spacing'>;
}
