// flow-typed signature: 67b458f1b74a0b412f53018e0b97eee4
// flow-typed version: <<STUB>>/retext-contractions_v^2.1.3/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-contractions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-contractions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-contractions/index' {
  declare module.exports: $Exports<'retext-contractions'>;
}
declare module 'retext-contractions/index.js' {
  declare module.exports: $Exports<'retext-contractions'>;
}
