// flow-typed signature: 53cd004b6ba9fc56cccf8877aa749e0e
// flow-typed version: <<STUB>>/retext-intensify_v^4.0.0/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-intensify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-intensify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-intensify/index' {
  declare module.exports: $Exports<'retext-intensify'>;
}
declare module 'retext-intensify/index.js' {
  declare module.exports: $Exports<'retext-intensify'>;
}
