// flow-typed signature: bbc019a3c8305dded8a4312403140faa
// flow-typed version: <<STUB>>/retext-redundant-acronyms_v^2.0.0/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-redundant-acronyms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-redundant-acronyms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-redundant-acronyms/index' {
  declare module.exports: $Exports<'retext-redundant-acronyms'>;
}
declare module 'retext-redundant-acronyms/index.js' {
  declare module.exports: $Exports<'retext-redundant-acronyms'>;
}
