// flow-typed signature: ee9c04302a8a2dd4c69524f35e4a690f
// flow-typed version: <<STUB>>/retext-repeated-words_v^1.2.2/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-repeated-words'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-repeated-words' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-repeated-words/index' {
  declare module.exports: $Exports<'retext-repeated-words'>;
}
declare module 'retext-repeated-words/index.js' {
  declare module.exports: $Exports<'retext-repeated-words'>;
}
