// flow-typed signature: 13ac2ba8315cb04b94648eb1ad522a4b
// flow-typed version: <<STUB>>/retext-diacritics_v^2.0.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-diacritics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-diacritics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'retext-diacritics/schema' {
  declare module.exports: any;
}

// Filename aliases
declare module 'retext-diacritics/index' {
  declare module.exports: $Exports<'retext-diacritics'>;
}
declare module 'retext-diacritics/index.js' {
  declare module.exports: $Exports<'retext-diacritics'>;
}
declare module 'retext-diacritics/schema.js' {
  declare module.exports: $Exports<'retext-diacritics/schema'>;
}
