// flow-typed signature: b8445a8fc5f6ac6afd955feaf2bdf1a2
// flow-typed version: <<STUB>>/rollup_v2.0.6/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup/dist/es/rollup.browser' {
  declare module.exports: any;
}

declare module 'rollup/dist/es/rollup' {
  declare module.exports: any;
}

declare module 'rollup/dist/es/shared/rollup' {
  declare module.exports: any;
}

declare module 'rollup/dist/es/shared/watch' {
  declare module.exports: any;
}

declare module 'rollup/dist/rollup.browser' {
  declare module.exports: any;
}

declare module 'rollup/dist/rollup' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/_events_commonjs-external' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/rollup' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup/dist/es/rollup.browser.js' {
  declare module.exports: $Exports<'rollup/dist/es/rollup.browser'>;
}
declare module 'rollup/dist/es/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/es/rollup'>;
}
declare module 'rollup/dist/es/shared/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/es/shared/rollup'>;
}
declare module 'rollup/dist/es/shared/watch.js' {
  declare module.exports: $Exports<'rollup/dist/es/shared/watch'>;
}
declare module 'rollup/dist/rollup.browser.js' {
  declare module.exports: $Exports<'rollup/dist/rollup.browser'>;
}
declare module 'rollup/dist/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/rollup'>;
}
declare module 'rollup/dist/shared/_events_commonjs-external.js' {
  declare module.exports: $Exports<'rollup/dist/shared/_events_commonjs-external'>;
}
declare module 'rollup/dist/shared/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/shared/rollup'>;
}
declare module 'rollup/dist/shared/watch.js' {
  declare module.exports: $Exports<'rollup/dist/shared/watch'>;
}
