<<<<<<< HEAD
// flow-typed signature: bea385dc0c87e9b66dd52fba7ba8c3e0
// flow-typed version: <<STUB>>/remark-preset-lint-markdown-style-guide_v2.1.3/flow_v0.120.1
=======
// flow-typed signature: fc07f86a3e8f77032ed2b7486b3a35c6
// flow-typed version: <<STUB>>/remark-preset-lint-markdown-style-guide_v2.1.3/flow_v0.119.1
>>>>>>> c3e414cabf8501d72ed4193c4f09dacf87b38582

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-preset-lint-markdown-style-guide'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-preset-lint-markdown-style-guide' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-preset-lint-markdown-style-guide/index' {
  declare module.exports: $Exports<'remark-preset-lint-markdown-style-guide'>;
}
declare module 'remark-preset-lint-markdown-style-guide/index.js' {
  declare module.exports: $Exports<'remark-preset-lint-markdown-style-guide'>;
}
