// flow-typed signature: 620a48ded2e862e627d90f85a410a23c
// flow-typed version: <<STUB>>/remark-lint-heading-style_v2.0.0/flow_v0.124.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-heading-style'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-heading-style' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-heading-style/index' {
  declare module.exports: $Exports<'remark-lint-heading-style'>;
}
declare module 'remark-lint-heading-style/index.js' {
  declare module.exports: $Exports<'remark-lint-heading-style'>;
}
