// flow-typed signature: 10e7e0ab346cf680fd5aac239f701ac9
// flow-typed version: <<STUB>>/unified_v8.3.2/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unified'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unified' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'unified/index' {
  declare module.exports: $Exports<'unified'>;
}
declare module 'unified/index.js' {
  declare module.exports: $Exports<'unified'>;
}
