<<<<<<< HEAD
// flow-typed signature: a5978ec25150cd21015e75faf69bf713
// flow-typed version: <<STUB>>/remark-lint-code-block-style_v1.0.3/flow_v0.120.1
=======
// flow-typed signature: 31683c9d21167988b4f8145d210378a4
// flow-typed version: <<STUB>>/remark-lint-code-block-style_v1.0.3/flow_v0.119.1
>>>>>>> c3e414cabf8501d72ed4193c4f09dacf87b38582

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-code-block-style'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-code-block-style' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-code-block-style/index' {
  declare module.exports: $Exports<'remark-lint-code-block-style'>;
}
declare module 'remark-lint-code-block-style/index.js' {
  declare module.exports: $Exports<'remark-lint-code-block-style'>;
}
