// flow-typed signature: 633914677297afb1ce593e4d9829e2a7
// flow-typed version: <<STUB>>/retext-syntax-mentions_v1.1.6/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-syntax-mentions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-syntax-mentions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-syntax-mentions/index' {
  declare module.exports: $Exports<'retext-syntax-mentions'>;
}
declare module 'retext-syntax-mentions/index.js' {
  declare module.exports: $Exports<'retext-syntax-mentions'>;
}
