// flow-typed signature: f1b3897debab2781ba6f8d32c520eadd
// flow-typed version: <<STUB>>/retext-english_v3.0.4/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-english'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-english' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-english/index' {
  declare module.exports: $Exports<'retext-english'>;
}
declare module 'retext-english/index.js' {
  declare module.exports: $Exports<'retext-english'>;
}
