// flow-typed signature: 1abd20ce5db572f434d2cdf56384dbeb
// flow-typed version: <<STUB>>/dictionary-en-us_v3.0.0/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dictionary-en-us'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dictionary-en-us' {
  declare module.exports: any;
}
