// flow-typed signature: 61993a2b88d8859b10fa42df9d518fa8
// flow-typed version: <<STUB>>/retext-syntax-urls_v2.0.0/flow_v0.124.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-syntax-urls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-syntax-urls' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-syntax-urls/index' {
  declare module.exports: $Exports<'retext-syntax-urls'>;
}
declare module 'retext-syntax-urls/index.js' {
  declare module.exports: $Exports<'retext-syntax-urls'>;
}
