<<<<<<< HEAD
// flow-typed signature: cc269e0035aca6a9cb8794f86137cf5d
// flow-typed version: <<STUB>>/@babel/plugin-transform-flow-strip-types_v7.8.3/flow_v0.120.1
=======
// flow-typed signature: a82f242b3a35d097183246f4f19f01e7
// flow-typed version: <<STUB>>/@babel/plugin-transform-flow-strip-types_v7.8.3/flow_v0.119.1
>>>>>>> c3e414cabf8501d72ed4193c4f09dacf87b38582

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-flow-strip-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-flow-strip-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-flow-strip-types/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-flow-strip-types/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-flow-strip-types/lib'>;
}
declare module '@babel/plugin-transform-flow-strip-types/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-flow-strip-types/lib'>;
}
