// flow-typed signature: 3cc5addfaf4fc98db8e28b8e426afe7c
// flow-typed version: <<STUB>>/dictionary-en_v3.0.0/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dictionary-en'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dictionary-en' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'dictionary-en/index' {
  declare module.exports: $Exports<'dictionary-en'>;
}
declare module 'dictionary-en/index.js' {
  declare module.exports: $Exports<'dictionary-en'>;
}
