// flow-typed signature: c4088197347019f531f38c3fbf54e60a
// flow-typed version: <<STUB>>/remark-preset-lint-markdown-style-guide_v2.1.2/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-preset-lint-markdown-style-guide'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-preset-lint-markdown-style-guide' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-preset-lint-markdown-style-guide/index' {
  declare module.exports: $Exports<'remark-preset-lint-markdown-style-guide'>;
}
declare module 'remark-preset-lint-markdown-style-guide/index.js' {
  declare module.exports: $Exports<'remark-preset-lint-markdown-style-guide'>;
}
