<<<<<<< HEAD
// flow-typed signature: c05f8361770a4b9c4551f5781dd46d16
// flow-typed version: <<STUB>>/@babel/plugin-proposal-pipeline-operator_v7.8.3/flow_v0.120.1
=======
// flow-typed signature: f1b5942914995d6a60b140fbaa01ef06
// flow-typed version: <<STUB>>/@babel/plugin-proposal-pipeline-operator_v7.8.3/flow_v0.119.1
>>>>>>> c3e414cabf8501d72ed4193c4f09dacf87b38582

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-pipeline-operator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-pipeline-operator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-pipeline-operator/lib/buildOptimizedSequenceExpression' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/lib/fsharpVisitor' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/lib' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/lib/minimalVisitor' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/lib/smartVisitor' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-pipeline-operator/lib/buildOptimizedSequenceExpression.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib/buildOptimizedSequenceExpression'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/fsharpVisitor.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib/fsharpVisitor'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/minimalVisitor.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib/minimalVisitor'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/smartVisitor.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib/smartVisitor'>;
}
