version: 2
jobs:
  build_and_check:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: yarn install
      - run: yarn run build
      - run: yarn run ci:precheck
      - run: yarn run check
      - run: yarn run ci:postcheck
workflows:
  version: 2
  build_and_check:
    jobs:
      - build_and_check
