version: 2
jobs:
  build_and_check:
    docker:
      - image: circleci/node:10
    steps:
      - git config --global user.email 'support@greenkeeper.io'
      - git config --global user.name 'greenkeeperio-bot'
      - checkout
      - run: yarn
      - run: yarn run install:pkgs
      - run: yarn run build
      - run: yarn run ci:precheck
      - run: yarn run check
      - run: yarn run ci:postcheck
workflows:
  version: 2
  build_and_check:
    jobs:
      - build_and_check
