version: 2
jobs:
  build_and_check:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn
      - run: yarn run install:pkgs
      - run: yarn run build
      - run: ./node_modules/.bin/greenkeeper-lockfile-update
      - run: yarn run check
      - run: ./node_modules/.bin/greenkeeper-lockfile-upload
workflows:
  version: 2
  build_and_check:
    jobs:
      - build_and_check
