version: 2
jobs:
  build_and_check:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn
      - run: yarn run install:pkgs
      - run: yarn run build
      - run: yarn run check
workflows:
  version: 2
  build_and_check:
    jobs:
      - build_and_check
