<<<<<<< HEAD
// flow-typed signature: 781c58713e488558cc030a31156a83fc
// flow-typed version: <<STUB>>/remark-lint-fenced-code-marker_v1.0.3/flow_v0.120.1
=======
// flow-typed signature: 73bcb9f33ec46c1ea39a0aa2be52d285
// flow-typed version: <<STUB>>/remark-lint-fenced-code-marker_v1.0.3/flow_v0.119.1
>>>>>>> c3e414cabf8501d72ed4193c4f09dacf87b38582

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-fenced-code-marker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-fenced-code-marker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-fenced-code-marker/index' {
  declare module.exports: $Exports<'remark-lint-fenced-code-marker'>;
}
declare module 'remark-lint-fenced-code-marker/index.js' {
  declare module.exports: $Exports<'remark-lint-fenced-code-marker'>;
}
