// flow-typed signature: 9ffd4a3f7097396e6ef2c8dc7fccc144
// flow-typed version: <<STUB>>/remark-lint-link-title-style_v^1.0.4/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-link-title-style'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-link-title-style' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-link-title-style/index' {
  declare module.exports: $Exports<'remark-lint-link-title-style'>;
}
declare module 'remark-lint-link-title-style/index.js' {
  declare module.exports: $Exports<'remark-lint-link-title-style'>;
}
