// flow-typed signature: 0b100a8b502bc5d98c2b81b81a3a2a77
// flow-typed version: <<STUB>>/remark-lint-emphasis-marker_v^1.0.3/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-emphasis-marker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-emphasis-marker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-emphasis-marker/index' {
  declare module.exports: $Exports<'remark-lint-emphasis-marker'>;
}
declare module 'remark-lint-emphasis-marker/index.js' {
  declare module.exports: $Exports<'remark-lint-emphasis-marker'>;
}
