// flow-typed signature: b1a7c0c41999adc152ab9b26ef0e3e14
// flow-typed version: <<STUB>>/remark-retext_v^3.1.3/flow_v0.124.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-retext'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-retext' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-retext/index' {
  declare module.exports: $Exports<'remark-retext'>;
}
declare module 'remark-retext/index.js' {
  declare module.exports: $Exports<'remark-retext'>;
}
