// flow-typed signature: c68ee33346a5fcd58d09a804b545e8e8
// flow-typed version: <<STUB>>/remark-lint-blockquote-indentation_v^1.0.3/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-blockquote-indentation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-blockquote-indentation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-blockquote-indentation/index' {
  declare module.exports: $Exports<'remark-lint-blockquote-indentation'>;
}
declare module 'remark-lint-blockquote-indentation/index.js' {
  declare module.exports: $Exports<'remark-lint-blockquote-indentation'>;
}
