// flow-typed signature: 2eb0fd53bb55327a63c8c6b739871da0
// flow-typed version: <<STUB>>/remark-lint-fenced-code-marker_v^1.0.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-fenced-code-marker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-fenced-code-marker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-fenced-code-marker/index' {
  declare module.exports: $Exports<'remark-lint-fenced-code-marker'>;
}
declare module 'remark-lint-fenced-code-marker/index.js' {
  declare module.exports: $Exports<'remark-lint-fenced-code-marker'>;
}
