// flow-typed signature: 4c1d50644c88f11ca70bc599bdfa6db9
// flow-typed version: <<STUB>>/remark-lint-code-block-style_v^1.0.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-code-block-style'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-code-block-style' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-code-block-style/index' {
  declare module.exports: $Exports<'remark-lint-code-block-style'>;
}
declare module 'remark-lint-code-block-style/index.js' {
  declare module.exports: $Exports<'remark-lint-code-block-style'>;
}
