// flow-typed signature: bce4435853c17ad7217bb25284798376
// flow-typed version: <<STUB>>/retext-passive_v2.0.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-passive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-passive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-passive/index' {
  declare module.exports: $Exports<'retext-passive'>;
}
declare module 'retext-passive/index.js' {
  declare module.exports: $Exports<'retext-passive'>;
}
