// flow-typed signature: 2856f36bd7d5e879c207509f242c796a
// flow-typed version: <<STUB>>/retext-contractions_v3.0.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-contractions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-contractions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-contractions/index' {
  declare module.exports: $Exports<'retext-contractions'>;
}
declare module 'retext-contractions/index.js' {
  declare module.exports: $Exports<'retext-contractions'>;
}
