// flow-typed signature: 38cb2420b7b299ee41dc89164426f7b9
// flow-typed version: <<STUB>>/retext-spell_v4.0.0/flow_v0.124.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-spell'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-spell' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-spell/index' {
  declare module.exports: $Exports<'retext-spell'>;
}
declare module 'retext-spell/index.js' {
  declare module.exports: $Exports<'retext-spell'>;
}
