// flow-typed signature: 9f091677cc73845f9a31159d63e9e0b3
// flow-typed version: <<STUB>>/remark-lint-table-cell-padding_v1.0.4/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-table-cell-padding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-table-cell-padding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-table-cell-padding/index' {
  declare module.exports: $Exports<'remark-lint-table-cell-padding'>;
}
declare module 'remark-lint-table-cell-padding/index.js' {
  declare module.exports: $Exports<'remark-lint-table-cell-padding'>;
}
