<<<<<<< HEAD
// flow-typed signature: 2587edb5c2cfc5fd6237056f7ac94467
// flow-typed version: <<STUB>>/remark-lint-emphasis-marker_v1.0.3/flow_v0.120.1
=======
// flow-typed signature: 0b8b0f08942f97c70d32f849841ee377
// flow-typed version: <<STUB>>/remark-lint-emphasis-marker_v1.0.3/flow_v0.119.1
>>>>>>> c3e414cabf8501d72ed4193c4f09dacf87b38582

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-emphasis-marker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-emphasis-marker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-emphasis-marker/index' {
  declare module.exports: $Exports<'remark-lint-emphasis-marker'>;
}
declare module 'remark-lint-emphasis-marker/index.js' {
  declare module.exports: $Exports<'remark-lint-emphasis-marker'>;
}
