// flow-typed signature: 527c2f2f0535d6526ccb0536ad5a6aeb
// flow-typed version: <<STUB>>/rollup-plugin-flow-entry_v0.3.4/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-flow-entry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-flow-entry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-flow-entry/lib' {
  declare module.exports: any;
}

declare module 'rollup-plugin-flow-entry/src/helpers' {
  declare module.exports: any;
}

declare module 'rollup-plugin-flow-entry/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-flow-entry/lib/index' {
  declare module.exports: $Exports<'rollup-plugin-flow-entry/lib'>;
}
declare module 'rollup-plugin-flow-entry/lib/index.js' {
  declare module.exports: $Exports<'rollup-plugin-flow-entry/lib'>;
}
declare module 'rollup-plugin-flow-entry/src/helpers.js' {
  declare module.exports: $Exports<'rollup-plugin-flow-entry/src/helpers'>;
}
declare module 'rollup-plugin-flow-entry/src/index' {
  declare module.exports: $Exports<'rollup-plugin-flow-entry/src'>;
}
declare module 'rollup-plugin-flow-entry/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-flow-entry/src'>;
}
