// @flow strict

export default {
  extends: ['stylelint-config-recommended'],
  plugins: ['stylelint-order'],
  rules: {
    'at-rule-name-case': ['lower'],
    'at-rule-name-space-after': ['always'],
    'at-rule-no-unknown': [true],
    'at-rule-semicolon-newline-after': ['always'],
    'block-closing-brace-newline-after': ['always'],
    'block-no-empty': [true],
    'block-opening-brace-space-after': ['always'],
    'color-hex-case': ['lower'],
    'color-hex-length': ['short'],
    'color-named': ['never'],
    'color-no-invalid-hex': [true],
    'comment-no-empty': [true],
    'comment-whitespace-inside': ['always'],
    'declaration-bang-space-after': ['always'],
    'declaration-block-no-duplicate-properties': [true, { ignore: ['consecutive-duplicates-with-different-values'] }],
    'declaration-block-no-redundant-longhand-properties': [true],
    'declaration-block-no-shorthand-property-overrides': [true],
    'declaration-block-semicolon-space-after': ['always-single-line'],
    'declaration-block-single-line-max-declarations': [4],
    'declaration-block-trailing-semicolon': ['always'],
    'declaration-colon-space-after': ['always'],
    'declaration-no-important': [true],
    'font-family-name-quotes': ['always-where-required'],
    'font-family-no-duplicate-names': [true],
    'font-family-no-missing-generic-family-keyword': null,
    'font-weight-notation': ['numeric', { ignore: 'relative' }],
    'function-calc-no-invalid': [true],
    'function-calc-no-unspaced-operator': [true],
    'function-comma-space-after': ['always'],
    'function-linear-gradient-no-nonstandard-direction': [true],
    'function-name-case': ['lower'],
    'function-parentheses-space-inside': ['never'],
    'function-url-quotes': ['never', { except: 'empty' }],
    'function-whitespace-after': ['always'],
    'indentation': [2],
    'keyframe-declaration-no-important': [true],
    'length-zero-no-unit': [true],
    'linebreaks': ['unix'],
    'media-feature-name-no-unknown': [true],
    'no-descending-specificity': [true],
    'no-duplicate-at-import-rules': [true],
    'no-duplicate-selectors': [true],
    'no-empty-first-line': [true],
    'no-empty-source': [true],
    'no-eol-whitespace': [true],
    'no-extra-semicolons': [true],
    'no-invalid-double-slash-comments': [true],
    'no-missing-end-of-source-newline': [true],
    'number-leading-zero': ['always'],
    'number-no-trailing-zeros': [true],
    'order/order': ['custom-properties', 'declarations'],
    'order/properties-alphabetical-order': true,
    'property-case': ['lower'],
    'property-no-unknown': [true],
    'property-no-vendor-prefix': [true],
    'rule-empty-line-before': ['always', { ignore: ['first-nested'] }],
    'selector-attribute-brackets-space-inside': ['never'],
    'selector-attribute-operator-space-after': ['never'],
    'selector-attribute-operator-space-before': ['never'],
    'selector-attribute-quotes': ['never'],
    'selector-combinator-space-after': ['always'],
    'selector-combinator-space-before': ['always'],
    'selector-descendant-combinator-no-non-space': [true],
    'selector-list-comma-space-after': ['always'],
    'selector-max-id': [0],
    'selector-no-qualifying-type': [true],
    'selector-pseudo-class-case': ['lower'],
    'selector-pseudo-class-no-unknown': [true, { ignorePseudoClasses: ['global'] }],
    'selector-pseudo-class-parentheses-space-inside': ['never'],
    'selector-pseudo-element-case': ['lower'],
    'selector-pseudo-element-colon-notation': ['double'],
    'selector-pseudo-element-no-unknown': [true],
    'selector-type-case': ['lower'],
    'selector-type-no-unknown': [true],
    'shorthand-property-no-redundant-values': [true],
    'string-no-newline': [true],
    'string-quotes': ['single'],
    'unit-case': ['lower'],
    'unit-no-unknown': [true],
    'value-keyword-case': ['lower'],
    'value-list-comma-space-after': ['always'],
    'value-no-vendor-prefix': [true],
  },
};
