// @flow strict

export default {
  rules: {
    'bin-type': 'error',
    'bundledDependencies-type': 'error',
    'config-type': 'error',
    'cpu-type': 'error',
    'dependencies-type': 'error',
    'description-format': ['error', { forbidEndingPeriod: true }],
    'description-type': 'error',
    'devDependencies-type': 'error',
    'directories-type': 'error',
    'engines-type': 'error',
    'files-type': 'error',
    'homepage-type': 'error',
    'keywords-type': 'error',
    'license-type': 'error',
    'main-type': 'error',
    'man-type': 'error',
    'name-format': 'error',
    'name-type': 'error',
    'no-duplicate-properties': 'error',
    'no-repeated-dependencies': 'error',
    'optionalDependencies-type': 'error',
    'os-type': 'error',
    'peerDependencies-type': 'error',
    'prefer-absolute-version-devDependencies': 'error',
    'prefer-alphabetical-bundledDependencies': 'error',
    'prefer-alphabetical-dependencies': 'error',
    'prefer-alphabetical-devDependencies': 'error',
    'prefer-alphabetical-optionalDependencies': 'error',
    'prefer-alphabetical-peerDependencies': 'error',
    'prefer-alphabetical-scripts': 'error',
    'prefer-property-order': ['error', [
      'name',
      'version',
      'description',
      'author',
      'bin',
      'bugs',
      'dependencies',
      'devDependencies',
      'optionalDependencies',
      'peerDependencies',
      'directories',
      'engines',
      'files',
      'homepage',
      'keywords',
      'license',
      'main',
      'module',
      'os',
      'preferGlobal',
      'private',
      'publishConfig',
      'repository',
      'scripts',
      'sideEffects',
    ]],
    'preferGlobal-type': 'error',
    'private-type': 'error',
    'repository-type': 'error',
    'require-author': 'error',
    'require-description': 'error',
    'require-homepage': 'error',
    'require-keywords': 'error',
    'require-license': 'error',
    'require-main': 'error',
    'require-module': 'error',
    'require-name': 'error',
    'require-repository': 'error',
    'require-version': 'error',
    'scripts-type': 'error',
    'version-format': 'error',
    'version-type': 'error',
  },
};
