// flow-typed signature: 42a30bf98ecd4ae8cab42b17774565b1
// flow-typed version: <<STUB>>/@babel/plugin-proposal-do-expressions_v7.5.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-do-expressions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-do-expressions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-do-expressions/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-do-expressions/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-do-expressions/lib'>;
}
declare module '@babel/plugin-proposal-do-expressions/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-do-expressions/lib'>;
}
