<<<<<<< HEAD
// flow-typed signature: d282cba3624ba17a2c999a6d2c1c9fcc
// flow-typed version: <<STUB>>/@babel/plugin-proposal-object-rest-spread_v7.8.3/flow_v0.120.1
=======
// flow-typed signature: 78ac788517acc0b1502b08d088d0319b
// flow-typed version: <<STUB>>/@babel/plugin-proposal-object-rest-spread_v7.8.3/flow_v0.119.1
>>>>>>> c3e414cabf8501d72ed4193c4f09dacf87b38582

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-object-rest-spread'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-object-rest-spread' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-object-rest-spread/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-object-rest-spread/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-object-rest-spread/lib'>;
}
declare module '@babel/plugin-proposal-object-rest-spread/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-object-rest-spread/lib'>;
}
