// flow-typed signature: edd2a2cbe16061e89b3b1cbcdd0626ec
// flow-typed version: <<STUB>>/retext-quotes_v3.0.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-quotes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-quotes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-quotes/index' {
  declare module.exports: $Exports<'retext-quotes'>;
}
declare module 'retext-quotes/index.js' {
  declare module.exports: $Exports<'retext-quotes'>;
}
