// flow-typed signature: 8d214430c6e27d0801709f3ae8277cfe
// flow-typed version: <<STUB>>/retext-equality_v4.5.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-equality'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-equality' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'retext-equality/en' {
  declare module.exports: any;
}

declare module 'retext-equality/lib/factory' {
  declare module.exports: any;
}

// Filename aliases
declare module 'retext-equality/en.js' {
  declare module.exports: $Exports<'retext-equality/en'>;
}
declare module 'retext-equality/index' {
  declare module.exports: $Exports<'retext-equality'>;
}
declare module 'retext-equality/index.js' {
  declare module.exports: $Exports<'retext-equality'>;
}
declare module 'retext-equality/lib/factory.js' {
  declare module.exports: $Exports<'retext-equality/lib/factory'>;
}
