// flow-typed signature: cc2aad3e5487b9e0374a9850a7cf4c8c
// flow-typed version: <<STUB>>/retext-assuming_v1.0.0/flow_v0.124.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-assuming'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-assuming' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-assuming/index' {
  declare module.exports: $Exports<'retext-assuming'>;
}
declare module 'retext-assuming/index.js' {
  declare module.exports: $Exports<'retext-assuming'>;
}
