// flow-typed signature: 4f09590d110860f36099ec7eafb820a9
// flow-typed version: <<STUB>>/@babel/plugin-proposal-optional-chaining_v7.2.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-optional-chaining'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-optional-chaining' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-optional-chaining/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-optional-chaining/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-optional-chaining/lib'>;
}
declare module '@babel/plugin-proposal-optional-chaining/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-optional-chaining/lib'>;
}
