// flow-typed signature: 375eef1e3b368c905b1bae85bb64adf0
// flow-typed version: <<STUB>>/@babel/plugin-external-helpers_v7.2.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-external-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-external-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-external-helpers/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-external-helpers/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-external-helpers/lib/index'>;
}
